### ISSUE TITLE
Pass closure in BlockOptimizerRatio Wrapped with DeepSpeed

### ISSUE THREAD

**Issue by a-F1** [Ledzy/BAdam#12]
Thank you for your excellent work. I noticed that BlockOptimizerRatio requires a closure parameter to be passed in during the step function. If I’m using DeepSpeed to wrap BlockOptimizerRatio, how should I provide this parameter?

I tried passing it directly, but I encountered the following error:
```
self.optimizer.step(step)
TypeError: DeepSpeedOptimizerWrapper.step() takes 1 positional argument but 2 were given
```

**Comment by Ledzy** [comment]
Thanks for your interest in our work! We only support Deepspeed for module-based partition. Please consider using `BlockOptimizer` instead of `BlockOptimizerRatio` if you need to run BAdam in a distributed manner.

**Comment by a-F1** [comment]
Thank you for your response! My issue has been resolved.
