### ISSUE TITLE
Error when using BlockOptimizerRatio

### ISSUE THREAD

**Issue by adf1178** [Ledzy/BAdam#7]
Thanks for your impressive work!

I have tried to run BlockOptimizer in my code which utilizes huggingface trainer and DeepSpeed Zero3. In the beginning there is an error which is solved by `model.enable_input_require_grads()`. The results is not good. So I change the optimizer. However, when I just change to  BlockOptimizerRatio, new error occurs:

When I use DeepSpeed Zero3, the error is 
`RuntimeError: copy_() between dense and sparse Tensors is not implemented! Found self type = CUDABFloat16Type and src type = SparseCUDABFloat16Type`

If I do not use DeepSeed, the error is:
`NotImplementedError: Cannot access storage of SparseTensorImpl`

How can I solve it and use BlockOptimizerRatio in my own code?
Thank you

**Comment by Ledzy** [comment]
Thank you for your interest in our work! The current code doesn't support distributed training yet; the result for `BlockOptimizer` may be logically incorrect. We are still actively developing the distributed version. Please keep an eye on our project :)

**Comment by adf1178** [comment]
Thanks for your reply! I will try non-distributed training setting.

**Comment by Ledzy** [comment]
Thanks for your interest on our project and your patience. We now support deepspeed ZeRO-3 when using BAdam `BlockOptimizer`, please see the detailed instruction here: https://github.com/Ledzy/BAdam?tab=readme-ov-file#partition-by-module-model-parallel.

**Comment by adf1178** [comment]
Thanks for your reply! I will try this.
