### ISSUE TITLE
Floating point exception when running sft with lora

### ISSUE THREAD

**Issue by Giyu917** [Ledzy/BAdam#8]
Hi, I‘m just wondering that do you have any ideas for the Floating point exception (core dumped) that occurs when running sft with lora in this project? I had tried using float32 when stepping the optimizer, but it didn't seem to work. Is it a problem with the torch environment or something? 
Your research and projects have really helped me a lot, thank you so much！

**Comment by Ledzy** [comment]
Hi @ZhichaoWang091732 , could you provide the full error message and the running command?

**Comment by Giyu917** [comment]
> Hi @ZhichaoWang091732 , could you provide the full error message and the running command?
Sure, I'm actually trying to sft llama-2-7b with LoRA. 
**The running command is** 
`CUDA_VISIBLE_DEVICES=0 python src/train_bash.py     --stage sft     --model_name_or_path meta-llama/Llama-2-7b     --do_train     --dataset alpaca_gpt4_en     --template default     --finetuning_type lora     --output_dir ./outputs/llama2-7b     --overwrite_cache     --per_device_train_batch_size 2     --per_device_eval_batch_size 2     --gradient_accumulation_steps 8     --lr_scheduler_type cosine     --logging_steps 1     --save_steps 1000     --val_size 500     --eval_steps 200     --evaluation_strategy steps     --learning_rate 1e-6     --num_train_epochs 3     --overwrite_output_dir     --plot_loss  --lora_target 'q_proj, v_proj'
`
**The full error message is as follows**
![image](https://github.com/Ledzy/BAdam/assets/46990927/c080fbe4-5c2f-4b9a-ae82-091f2e5cb06e)

Thank you so much for your time and reply.

**Comment by Ledzy** [comment]
The provided command trains the LoRA model without using BAdam. In this case, you should set `--bf16` flag to enable mixed-precision training. We recommend to use the latest code of [Llama Factory](https://github.com/hiyouga/LLaMA-Factory) to conduct your experiment.
